export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const ADD_CONSULTANT = 'ADD_CONSULTANT';
export const UPDATE_CONSULTANT = 'UPDATE_CONSULTANT';
export const REMOVE_CONSULTANT = 'REMOVE_CONSULTANT';
export const ADD_PROFILE = 'ADD_PROFILE';
